export interface PetCarerProfile {
    firstName: string,
    lastName: string,
    email: string,
    city: string,
    province: string,
    postcode: string,
    country: string,
    dob: any,
    phone: any,
    photo: any,
    breedPref: string,
    carerNeighbor: string,
    aboutCarer: string,
    bgcheck: any,  
    hPrice: any,  
}